export const FETCH_TOWNS_START = 'FETCH_TOWNS_START'
export const FETCH_TOWNS_SUCCESS = 'FETCH_TOWNS_SUCCESS'
export const FETCH_TOWNS_FAILURE = 'FETCH_TOWNS_FAILURE'

export const FETCH_HOURLY_START = 'FETCH_HOURLY_START'
export const FETCH_HOURLY_SUCCESS = 'FETCH_HOURLY_SUCCESS'
export const FETCH_HOURLY_FAILURE = 'FETCH_HOURLY_FAILURE'

export const FETCH_FOR_WEEK_START = 'FETCH_FOR_WEEK_START'
export const FETCH_FOR_WEEK_SUCCESS = 'FETCH_FOR_WEEK_SUCCESS'
export const FETCH_FOR_WEEK_FAILURE = 'FETCH_FOR_WEEK_FAILURE'

export const ADD_TO_RECENTLY_VIEWED = 'ADD_TO_RECENTLY_VIEWED'